apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinates-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: coordinates-api-1

  template:
    metadata:
      labels:
        app: coordinates-api-1
        tier: application
    spec:
      containers:
      - name: api
        image: mma44331/coordinates_api:v1

        ports:
        - containerPort: 8000
          name: http

        env:
        - name: POSTGRES_HOST
          value: "postgres1-0.postgres-svc"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "coordinates_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"

