apiVersion: v1
kind: Service
metadata:
  name: coordinates-api-svc
  labels:
    app: coordinates-api-svc
    tier: application
spec:
  type: NodePort
  selector:
    app: coordinates-api-1
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    name: http
    protocol: TCP


